name: 'Test & Coverage'
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    
    - name: 'Install pnpm'
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false
        
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: 'Get pnpm store directory'
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
          
    - name: 'Install Dependencies'
      run: pnpm install
      
    - name: 'Test'
      run: pnpm vitest --coverage.enabled true
      
    - name: 'Report Coverage'
      if: always()
      uses: davelosert/vitest-coverage-report-action@v2

